steps:
# 1. Install dependencies (Node 20)
- name: 'node:20' 
  id: 'Install Dependencies'
  entrypoint: 'npm'
  args: ['install']
  
# 2. Build the React/Vite app (Node 20)
- name: 'node:20'
  id: 'Build Application'
  entrypoint: 'npm'
  args: ['run', 'build']
  
# 3. Deploy to App Engine - CORRECTED
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Deploy to App Engine'
  # Set the command itself as the entrypoint
  entrypoint: 'gcloud' 
  args: [
    'app', 
    'deploy'
  ]
  
options:
  logging: CLOUD_LOGGING_ONLY